[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "wisdom nice enter carbon dose hospital general panel invest bronze extend banana web blanket icon merge torch shock material tip have knife price what"
